version: '2'
services:
  borg-client:
    image: registry.gitlab.com/devops_containers/dockers/borg-client:1.1.16-alpine-v1.0.1
    build: 
      context: build/borg-client/.
      args:
        APP_VERSION: "1.1.16"
        BASE_IMAGE: "alpine:edge"
        RUN_USER: "human"
    container_name: borg-client
