version: '2'
services:
  borg-client:
    image: devsadds/borg-client:1.1.17.01
    build: 
      context: build/borg-client/.
      args:
        APP_VERSION: "1.1.17-r0"
        BASE_IMAGE: "alpine:edge"
        RUN_USER: "human"
    container_name: borg-client
