version: "3.4"
services:

  kibana:
    image: "amazon/opendistro-for-kibana:0.7.1"
    container_name: odfe-kibana
    volumes:
      - "/docker-compose/SWARM/elasticsearch/configs/kibana:/usr/share/kibana/config"
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://odfe-masternode1:9200
      - opendistro_security.multitenancy.enabled=false
    networks:
      odfe-net:
        aliases:
          - kibana
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 1200M
        reservations:
          memory: 4M  
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 50
        window: 20s
      update_config:
        parallelism: 1
        delay: '3s'
        failure_action: continue
        monitor: '3s'
        max_failure_ratio: 0.3
      placement:
        constraints: [ node.labels.prod1-service04 == true ]



  odfe-masternode1:
    image: "amazon/opendistro-for-elasticsearch:0.7.1"
    container_name: odfe-masternode1
    hostname: odfe-masternode1
    environment:
      - "cluster.name=logs2"
      #- "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "opendistro_security.ssl.http.enabled=false"
      - "discovery.zen.minimum_master_nodes=1"
      - "discovery.zen.ping.unicast.hosts=odfe-masternode1"
      - "node.name=odfe-masternode1"
      - "node.master=true"
      - "node.data=false"
      - "node.ingest=true"
      - "network.bind_host=0.0.0.0"
      - "network.publish_host=_eth0_"
      - "http.host=0.0.0.0"
      - "network.host=0.0.0.0"
      - "discovery.type=zen"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /docker-compose-data/masternode1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
      - "9600:9600"
    networks:
      odfe-net:
        aliases:
          - odfe-masternode1
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 2400M
        reservations:
          memory: 4M  
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 50
        window: 20s
      update_config:
        parallelism: 1
        delay: '3s'
        failure_action: continue
        monitor: '3s'
        max_failure_ratio: 0.3
      placement:
        constraints: [ node.labels.prod1-service04 == true ]




  odfe-datanode1:
    image: "amazon/opendistro-for-elasticsearch:0.7.1"
    #container_name: odfe-datanode1
    hostname: odfe-datanode1
    environment:
      - "cluster.name=logs2"
      #- "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - "opendistro_security.ssl.http.enabled=false"
      - "discovery.zen.minimum_master_nodes=1"
      - "discovery.zen.ping.unicast.hosts=odfe-masternode1"
      - "node.name=odfe-datanode1"
      - "node.master=false"
      - "node.data=true"
      - "node.ingest=false"
      - "network.bind_host=0.0.0.0"
      - "network.publish_host=_eth0_"
      - "http.host=0.0.0.0"
      - "network.host=0.0.0.0"
      - "discovery.type=zen"
    volumes:
      - /docker-compose-data/odfe-data1:/usr/share/elasticsearch/data
    networks:
      odfe-net:
        aliases:
          - odfe-datanode1
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 3800M
        reservations:
          memory: 4M  
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 50
        window: 20s
      update_config:
        parallelism: 1
        delay: '3s'
        failure_action: continue
        monitor: '3s'
        max_failure_ratio: 0.3
      placement:
        constraints: [ node.labels.prod1-service05 == true ]




  odfe-datanode2:
    image: "amazon/opendistro-for-elasticsearch:0.7.1"
    container_name: odfe-datanode2
    environment:
      - "cluster.name=logs2"
      #- "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - "opendistro_security.ssl.http.enabled=false"
      - "discovery.zen.minimum_master_nodes=1"
      - "discovery.zen.ping.unicast.hosts=odfe-masternode1"
      - "node.name=odfe-datanode2"
      - "node.master=false"
      - "node.data=true"
      - "node.ingest=false"
      - "network.bind_host=0.0.0.0"
      - "network.publish_host=_eth0_"
      - "http.host=0.0.0.0"
      - "network.host=0.0.0.0"
      - "discovery.type=zen"
    volumes:
      - /docker-compose-data/odfe-data2:/usr/share/elasticsearch/data
    networks:
      odfe-net:
        aliases:
          - odfe-datanode2
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 3800M
        reservations:
          memory: 4M  
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 50
        window: 20s
      update_config:
        parallelism: 1
        delay: '3s'
        failure_action: continue
        monitor: '3s'
        max_failure_ratio: 0.3
      placement:
        constraints: [ node.labels.prod1-service06 == true ]

  odfe-datanode3:
    image: "amazon/opendistro-for-elasticsearch:0.7.1"
    container_name: odfe-datanode3
    environment:
      - "cluster.name=logs2"
      #- "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - "opendistro_security.ssl.http.enabled=false"
      - "discovery.zen.minimum_master_nodes=1"
      - "discovery.zen.ping.unicast.hosts=odfe-masternode1"
      - "node.name=odfe-datanode3"
      - "node.master=false"
      - "node.data=true"
      - "node.ingest=false"
      - "network.bind_host=0.0.0.0"
      - "network.publish_host=_eth0_"
      - "http.host=0.0.0.0"
      - "network.host=0.0.0.0"
      - "discovery.type=zen"
    volumes:
      - /docker-compose-data/odfe-data3:/usr/share/elasticsearch/data
    networks:
      odfe-net:
        aliases:
          - odfe-datanode3
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 3800M
        reservations:
          memory: 4M  
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 50
        window: 20s
      update_config:
        parallelism: 1
        delay: '3s'
        failure_action: continue
        monitor: '3s'
        max_failure_ratio: 0.3
      placement:
        constraints: [ node.labels.prod1-service07 == true ]


  odfe-datanode4:
    image: "amazon/opendistro-for-elasticsearch:0.7.1"
    container_name: odfe-datanode4
    environment:
      - "cluster.name=logs2"
      #- "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - "opendistro_security.ssl.http.enabled=false"
      - "discovery.zen.minimum_master_nodes=1"
      - "discovery.zen.ping.unicast.hosts=odfe-masternode1"
      - "node.name=odfe-datanode4"
      - "node.master=false"
      - "node.data=true"
      - "node.ingest=false"
      - "network.bind_host=0.0.0.0"
      - "network.publish_host=_eth0_"
      - "http.host=0.0.0.0"
      - "network.host=0.0.0.0"
      - "discovery.type=zen"
    volumes:
      - /docker-compose-data/odfe-data4:/usr/share/elasticsearch/data
    networks:
      odfe-net:
        aliases:
          - odfe-datanode4
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 3800M
        reservations:
          memory: 4M  
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 50
        window: 20s
      update_config:
        parallelism: 1
        delay: '3s'
        failure_action: continue
        monitor: '3s'
        max_failure_ratio: 0.3
      placement:
        constraints: [ node.labels.prod1-service08 == true ]


  cerebro:
    image: "lmenezes/cerebro:0.8.2"
    container_name: cerebro
    ports:
      - 19000:9000
    networks:
      odfe-net:
        aliases:
          - cerebro
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          memory: 4M  
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 50
        window: 20s
      update_config:
        parallelism: 1
        delay: '3s'
        failure_action: continue
        monitor: '3s'
        max_failure_ratio: 0.3
      placement:
        constraints: [ node.labels.prod1-service04 == true ]


################################
# ELASTICSEARCH OVERLAY NETWORK #
################################
networks:
  odfe-net:
    driver: overlay
