###CONFIGMAP
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: prod-01
  labels:
    node.role: datebase
data:
  POSTGRES_DB: demopostgresdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Kmsdksdkjjfdfdfdfdf