###DEPLOYMENT flaskdeploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-13
  namespace: prod-01
  labels:
    node.role: datebase
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      node.role: datebase
  template:
    metadata:
      labels:
        node.role: datebase
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.role
                operator: In
                values:
                - datebase
      containers:
      - name: postgres-13
        image: devsadds/postgres:13.2
        imagePullPolicy: Always
        ports:
          - containerPort: 5432
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: "services-pgdata"
        envFrom:
          - configMapRef:
              name: postgres-config
      volumes:
        - hostPath:
            path: "/docker-compose-local/volumes/postgres13"
          name: services-pgdata
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30


