apiVersion: apps/v1
#kind: Deployment
kind: StatefulSet
metadata:
  name: postgres-13
  namespace: prod-01
  labels:
    app: postgres
spec:
  serviceName: "postgres-13"
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:  
      containers:
        - name: postgres-13
          image: devsadds/postgres:13.2
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "services-pgdata"
          envFrom:
          - configMapRef:
              name: postgres-config
      volumes:
        - hostPath:
            path: "/docker-compose-local/volumes/postgres13"
          name: services-pgdata



