version: '2'
services:
  php:
    image: registry.gitlab.com/devops_containers/dockers/php:8.0.8-fpm-alpine3.14
    build: 
      context: build/php/.
      args:
        BASE_IMAGE: "php:8.0.8-fpm-alpine3.14"
        DOCKER_IMAGE_VERSION: "1.0.0"
    container_name: php