version: '2'
services:
  awx_task:
    image: registry.gitlab.com/devops_containers/dockers/awx_task:11.2.0
    build: 
      context: build/awx_task/.
      args:
        IMAGE_TAG: "ansible/awx_task:11.2.0"
    #entrypoint: tail -f /dev/null
    container_name: awx_task