---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: nginx-proxy
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-proxy
      namespace: nginx-proxy
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.0
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: nginx-proxy
  labels:
    app: worker-node
spec:
  selector:
    app: worker-node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: nginx-proxy
  labels:
    app: worker-node
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 80
  externalIPs:
    - 192.168.122.152
  selector:
    app: worker-node
    tier: frontend
#kubectl label nodes vm104  k8s-app=traefik-ingress-lb --overwrite
#ubectl get svc -n kube-system