apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-volume
  namespace: production
  labels:
    type: local
    node.role: worker
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /docker-compose-local/volumes/flask
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node.role
          operator: In
          values:
            - worker

