version: "3.8"

x-logging:
  &rsyslog-logging
  driver: syslog
  options:
    syslog-address: "udp://127.0.0.1:515"

x-logging-json:
  &json-logging
  driver: json-file
  options:
    max-size: '100m'
    max-file: '5'

x-deploy:
  &redis-deploy
  #mode: global
  replicas: 1
  #endpoint_mode: dnsrr
  restart_policy:
    condition: on-failure
    delay: 10s
    max_attempts: 40
    window: 10s
  update_config:
    parallelism: 1
    delay: 5s
    failure_action: rollback
    monitor: 25s
    max_failure_ratio: 0.3
    order: stop-first
  placement:
    constraints: [ node.labels.redis == true ]

services:
  redis:
    image: "${DOCKER_IMAGE_REDIS}"
    hostname: "{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}"
    volumes:
      - redis-1:/bitnami/redis/data
    environment:
        DOCKER_ROLE: "${DOCKER_ROLE}"
        DISCOVERY_SERVICE: "${DISCOVERY_SERVICE}"
        #
        ALLOW_EMPTY_PASSWORD: "${ALLOW_EMPTY_PASSWORD}"
    sysctls:
      net.core.somaxconn: 4048
      net.ipv4.ip_local_port_range: "1024 65535"
    configs:
      - source: limits.conf
        target: /etc/security/limits.con

    networks:
      pxc_percona_net:
    deploy:
      <<: *redis-deploy

volumes:
  redis-1:

configs:
  limits.conf:
    file: ./limits.conf

networks:
  pxc_percona_net:
    external: ${DOCKER_NETWORK_EXTERNAL_REDIS}
    driver: ${DOCKER_NETWORK_DRIVER_REDIS}
