version: '2'
services:
  postgresql-repmgr:
    image: devsadds/postgresql-repmg:13.2.0-v1.1.0
    build: 
      context: build/from-stratch/.
      args:
        BASE_IMAGE: "docker.io/bitnami/minideb:buster"
        TIMESCALE_VERSION: "2.1.0"
    container_name: postgresql-repmgr
