version: '2'
services:
  elasticsearch:
    image: registry.gitlab.com/devops_containers/dockers/elasticsearch:7.13.0
    build: 
      context: build/elasticsearch/.
      args:
        IMAGE_TAG: "docker.elastic.co/elasticsearch/elasticsearch:7.13.0"
    container_name: elasticsearch