version: '2'
services:
  grafana:
    image: registry.gitlab.com/devops_containers/dockers/grafana:8.0.1-ubuntu
    build: 
      context: build/grafana/.
      args:
        APP_VERSION: "0.2.4"
        BASE_IMAGE: "grafana/grafana:8.0.1-ubuntu"
        RUN_USER: "human"
    container_name: grafana