version: '3.8'

services:

  haproxy-postgres:
    image: registry.gitlab.com/devops_containers/dockers/haproxy-postgres:2.4.1_consul_v1.1.0
    build: 
      context: build/haproxy-postgres/.
      args:
        BASE_IMAGE : "registry.gitlab.com/devops_containers/dockers/haproxy-mysql:2.4.1_consul_v1.1.0"
    environment:
      HAPROXY_TIMEOUT_CLIENT: "1h"
      HAPROXY_TIMEOUT_SERVER: "1h"
      HAPROXY_TIMEOUT_CONNECT: "1h"

