version: '3.8'

services:

  haproxy-postgres:
    image: devsadds/haproxy-postgres:2.4.1_consul_v1.0.2
    build: 
      context: build/haproxy-postgres/.
      args:
        BASE_IMAGE : "devsadds/haproxy-mysql:2.4.1_consul_v1.0.2"
    environment:
      HAPROXY_TIMEOUT_CLIENT: "1h"
      HAPROXY_TIMEOUT_SERVER: "1h"
      HAPROXY_TIMEOUT_CONNECT: "1h"

