version: "3.8"

x-logging:
  &rsyslog-logging
  driver: syslog
  options:
    syslog-address: "udp://127.0.0.1:515"

x-logging-json:
  &json-logging
  driver: json-file
  options:
    max-size: '100m'
    max-file: '5'


services:
  pgbouncer:
    image: devsadds/pgbouncer:1.15.0-consul-v1.0.0
    ports:
      - 6432:6432
    environment:
        #
        DOCKER_ROLE: "pgbouncer"
        #
        DATABASES_HOST: "10.50.0.10"
        DATABASES_PORT: "5432"
        DATABASES_USER: "smssender"
        DATABASES_PASSWORD: "smssender"
        DATABASES_DBNAME: "smssender"
        #
        DATABASES_POOL_SIZE: "20"
        DATABASES_RESERVE_POOL: "10"
        #DATABASES_CONNECT_QUERY: ""
        DATABASES_POOL_MODE: "transaction"
        DATABASES_MAX_DB_CONNECTIONS: "100"
        DATABASES_CLIENT_ENCODING: "UNICODE"
        DATABASES_DATESTYLE: "iso"
        #DATABASES_TIMEZONE: ""
        #DATABASES_CONNECT_QUERY: "SELECT 1"
        #
        PGBOUNCER_LISTEN_ADDR: "0.0.0.0"
        PGBOUNCER_LISTEN_PORT: "6432"
        PGBOUNCER_LOGFILE: "/tmp/pg.log"
        PGBOUNCER_MAX_CLIENT_CONN: "3000"
        PGBOUNCER_DEFAULT_POOL_SIZE: "20"
        #
        DISCOVERY_SERVICE: "consul"
        DISCOVERY_SERVICE_HOST: "consul"
        DISCOVERY_SERVICE_NAME: "pgbouncer"


