version: "3.8"

x-logging:
  &rsyslog-logging
  driver: syslog
  options:
    syslog-address: "udp://127.0.0.1:515"

x-logging-json:
  &json-logging
  driver: json-file
  options:
    max-size: '100m'
    max-file: '5'

x-deploy:
  &haproxy-deploy
  mode: global
  #replicas: 1
  endpoint_mode: dnsrr
  restart_policy:
    condition: on-failure
    delay: 10s
    max_attempts: 40
    window: 10s
  update_config:
    parallelism: 1
    delay: 5s
    failure_action: rollback
    monitor: 25s
    max_failure_ratio: 0.3
    order: stop-first
  placement:
    constraints: [ node.labels.haproxy-mysql  == true ]


services:
  haproxy:
    image: devsadds/haproxy-mysql:2.4-dev9_consul-1.9.3_consul-template-0.25.1-v1.3.0
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
      - target: 3307
        published: 3307
        protocol: tcp
        mode: host
      - target: 80
        published: 33380
        protocol: tcp
        mode: host      
      - target: 19101
        published: 19102
        protocol: tcp
        mode: host
    environment:
        DOCKER_ROLE: "haproxy"
        DISCOVERY_SERVICE: "consul"
        DISCOVERY_SERVICE_HOST: "consul"
        DISCOVERY_SERVICE_NAME: "pxc"
        HAPROXY_STATS_URL: "/"
        HAPROXY_STATS_AUTH_USER: "user"
        HAPROXY_STATS_AUTH_PASSWORD: "password"
        HAPROXY_STATS_ALLOW_HOSTS: "192.168.0.0/12 10.0.0.0/8 172.16.0.0/12 127.0.0.1/32"
        HAPROXY_SERVICE_ALLOW_HOSTS: "192.168.0.0/12 10.0.0.0/8 172.16.0.0/12 127.0.0.1/32"
        SERVER_NAME: "haproxy"
        HAPROXY_MYSQL_CHECK_USER: "hpclustercheckuser"
        HAPROXY_MYSQL_BACKEND_MAX_CONN: "200"
        SERVER_INTERFACE_BIND: "ethwe0"
    networks:
      pxc_percona_net:
    deploy:
      <<: *haproxy-deploy


networks:
  pxc_percona_net:
    external: true
    driver: weaveworks/net-plugin:2.8.1
    ipam:
      driver: default