apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-13-01
  namespace: production
  labels:
    type: local
    node.role: datebase
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
    #storage: ""
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /docker-compose-local/volumes/postgres-13-01
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node.role
          operator: In
          values:
            - datebase

