---
apiVersion: v1
kind: Service
metadata:
  name: svc-postgres-13
  namespace: production
  labels:
    node.role: datebase
  #annotations:
  #  service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
  #  service.beta.kubernetes.io/do-loadbalancer-size-slug: "lb-large"
  #  service.beta.kubernetes.io/do-loadbalancer-protocol: "tcp"
spec:
  type: NodePort # NodePort,LoadBalancer,ClusterIP,ExternalName
  #externalTrafficPolicy: Cluster # expose or not on external ip Nodeport. Values:  Cluster,Local
  ports:
  - name: postgres-13-5432
    protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30050
  selector:
    node.role: datebase
